apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iq7fsy2ui-nodejs 
  janus-idp.io/tekton: iq7fsy2ui-nodejs
  backstage.io/kubernetes-id: iq7fsy2ui-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iq7fsy2ui-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml