apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iq7fsy2ui-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iq7fsy2ui-nodejs 
  name: iq7fsy2ui-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: iq7fsy2ui-nodejs 
