apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: iq7fsy2ui-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0f8f3b5dff.s9s3.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:4911358b4ed18fca613ee30f5b73a1adaf6b4258@sha256:5b01011b9ac04f2ca3dc352e71e5ec469469239553e0204b3f5128ce43a490cb
          name: container-image
